### ISSUE TITLE
missing data file

### ISSUE THREAD

**Issue by Horace89** [AehLane/BoneTrade-Project-OSLNN#1]
Where can I find a copy of `data_copy_with_equal_augs.zip`?

**Comment by AehLane** [comment]
This is more of a personal repo as I continue to develop the BoneTrade Project's codebase. At the moment, our lab research group is still in the process of training the neural network and analyzing our dataset. I don't expect us to properly clean up our code, and possibly add samples, until sometime later this month at the earliest

That said, you can find a Colab notebook here, https://github.com/bonetrade/one-shot-learning, to create "augmented images". "data_copy_with_equal_augs.zip" is just a temporary dataset for training the network during development composed of augmented images created from a select group of dry specimens of known providence.
